#!/usr/bin/env python

"""
Convert 3 letter months to numerical versions, eg:

    31Jan2015 -> 31-01-2015

"""

import fileinput
import re
import sys


def month_sub(m):
    months = {
        'Jan': '01',
        'Feb': '02',
        'Mar': '03',
        'Apr': '04',
        'May': '05',
        'Jun': '06',
        'Jul': '07',
        'Aug': '08',
        'Sep': '09',
        'Oct': '10',
        'Nov': '11',
        'Dec': '12',
    }
    month = months.get(m.group(2), '')
    return '{}/{}/{}'.format(m.group(1), month, m.group(3))

for line in fileinput.input():
    sys.stdout.write(re.sub(r'^(\d{2})\s(\w{3})\s(\d{4})', month_sub, line))
