#!/bin/bash

set -e

tmp="tmp.csv"

# loop inputs
for file; do
    # remove header
    # replace string dates for numbers
    # fix date order (dd/mm/yyyy -> yyyy-mm-dd)
    # remove blank lines
    # sort and uniq
    tail -n +4 "$file" | \
        ./fix-dates | \
        sed -E 's/^(..)\/(..)\/(....)(.*)/\3-\2-\1\4/' | \
        sed -E '/^$/d' | \
        sort | uniq > "$tmp"

    accounts=$(gawk '{sub(/\"\047/, "", $7); sub(/\"\r?$/, "", $7); print $7}' FPAT="([^,]*)|(\"[^\"]+\")" "$tmp" | sort | uniq)

    # Extract accounts and loop
    for account in $accounts; do
        # make sure account directory exists
        mkdir -p "$account"

        # Extract years from transaction in given account and loop
        for year in $(grep "$account" "$tmp" | awk -F '-' '{print $1}' | sort | uniq); do
            # extract transactions using year and account
            egrep -i "$year.*$account" "$tmp" > tmp-sorted.csv

            target="$account/$year.csv"
            # make sure target file exists
            touch "$target"

            # combine existing target file with output to avoid duplicates/overwriting
            cat "$target" >> tmp-sorted.csv
            sort tmp-sorted.csv | uniq > "$target"
        done
    done
done

# tidy up
rm tmp{,-sorted}.csv
