#!/bin/bash

set -eu

output=$1
tmp="tmp.csv"

# loop inputs
for file in "${@:2}"; do
    # remove header (first line)
    tail -n +2 "$file" | \

    # flip date format from DD/MM/YYYY -> YYYY/MM/DD
    sed -E 's/^(..)(....)(....)/\3\2\1/' | \

    # remove non-ascii chars
    iconv -c -f utf-8 -t ascii | \

    # sort into temp file
    sort > "$tmp"

    # seperate transactions into $year-tmp files
    awk -F '/' '{print $0 >> $1"-tmp"}' "$tmp"

    # merge each year-tmp file with existing transactions for that year
    for year in $(awk -F '/' '{print $1}' "$tmp" | sort | uniq); do
        # define files
        file="$output/$year.csv"
        target="$year-tmp"

        # make sure final target file exists
        touch "$file"

        # combine existing file into year-tmp file
        cat "$file" >> "$target"

        # sort and dedupe year-tmp file into existing file
        sort "$target" | uniq > "$file"

        # tidy up year tmp file
        rm "$target"
    done
done

# tidy up
rm $tmp
